config/routes.rb
Rails.application.routes.draw do
  get 'api/news', to: 'api#index'
  get 'api/:start_date/:end_date', to: 'api#show'
  post 'api/tweets', to: 'api#create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'users/index'
  
  resources :tweets do
    post :retweet, to:'tweets/retweet'
    post :friend
    delete :unfriend
    resources :likes
  end
  
  get '/tweets/hashtag/:name', to: 'tweets#hashtags'
  
  root 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :retweets, class_name: 'Tweet', foreign_key: :retweet_id, dependent: :destroy
  belongs_to :tweet, class_name: 'Tweet', optional: true    
  scope :tweets_for_me, ->(friends) {where(user_id: friends)}

  has_and_belongs_to_many :tags

  validates :content, presence: :true, length: { maximum: 140}

  after_create do
      tweet = Tweet.find_by(id: self.id)
      hashtags = self.content.scan(/#\w+/)
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        self.tags << tag
      end
    end
  
      before_update do
      self.tags.clear
      hashtags = self.content.scan(/#\w+/)
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        self.tags << tag
      end
    end  

  def to_s
      content
  end
  
  def liked?(user)
    !!self.likes.find{|like| like.user_id == user.id}
  end

  def retweet?(user) 
    self.retweets.find{|retweet| retweet.user_id == user.id}
  end


    #paginate_per  25  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :set_tweet, only: [ :show, :edit, :update, :destroy ]
    before_action :set_current_tweet, only:[:like, :retweet]
    before_action :authenticate_user! #except: [:index, :show]
    
    # GET /tweets or /tweets.json
    def index
      @q = Tweet.page(params[:page]).ransack(params[:q])
      @tweets = @q.result(distinct: true)
      @tweet = Tweet.new
    end
     
  
    # GET /tweets/1 or /tweets/1.json
    def show
      @tweets = Tweet.all
      #@retweet = Tweet.find_by(id: @tweet.tweet_id)
    end
  
    # GET /tweets/new
    def new 
      @tweet = current_user.tweets.build
    end
  
    # GET /tweets/1/edit
    def edit
    end
  
    # POST /tweets or /tweets.json
    def create
      @tweet = Tweet.new(tweet_params.merge(user: current_user))  #para llamar al usuario conectado
  
      respond_to do |format|
        if @tweet.save
          format.html { redirect_to root_path, notice: "Tweet was successfully created." }
          format.json { render :show, status: :created, location: @tweet }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /tweets/1 or /tweets/1.json
    def update
      respond_to do |format|
        if @tweet.update(tweet_params)
          format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
          format.json { render :show, status: :ok, location: @tweet }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /tweets/1 or /tweets/1.json
    def destroy
      @tweet.destroy
      respond_to do |format|
        format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    # like
    def like
      @tweet = Tweet.all.find(params[:id])
      Like.create(user_id: current_user.id, tweet_id: @tweet.id)
      redirect_to tweet_path(@tweet)
    end 
  
    def unlike    #arreglar
      @tweet = Tweet.all.find(params[:id])
      Like.destroy(user_id: current_user.id, tweet_id: @tweet.id)
      redirect_to tweet_path(@tweet)
    end
  
    # Retweet
    def retweet
      if @tweet
        Tweet.create(user_id: current_user.id, content: "Este Tweet pertenece a: #{@tweet.user.name}: #{@tweet.content}", retweet_id: @tweet.id)
        redirect_to root_path, notice: "Was Retweet!"
      end
      #version choca con callback
      # if @tweet
      #   @tweet = Tweet.new(tweet_params.merge(user: current_user))
      # redirect_to new_tweet_path(tweet) #pendiente de la vista, no resulta.  
      # end
    end

    def friend
      @friend = @user.friend.create(user_id: current_user.id, friend_id: @tweet.user.id)
      redirect_to root_path, notice: "Siguiendo"
    end
  
    def unfriend
      @friend = Friend.find_by(friend_id: @tweet.user.id)
      @friend.destroy
      redirect_to root_path, notice: "Dejaste de seguirlo"
    end

    def hashtags
      tag = Tag.find_by(name: params[:name])
      @q = Tag.ransack(params[:q])
      @tweets = @q.result(distinct: true)
      @tweets = tag.tweets
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_tweet
        @tweet = Tweet.find(params[:id])
      end
  
      def set_current_tweet
        @tweet = Tweet.find(params[:tweet_id])
      end
  
      # Only allow a list of trusted parameters through.
      def tweet_params
        params.require(:tweet).permit(:content, :user_id)
      end
  
  
       
  end
  

app/helpers/tweets_helper.rb
module TweetsHelper
    def render_with_hashtags(content)
        content.gsub(/#\w+/){|w| link_to w, "tweets/hashtag/#{w.delete('#')}"}.html_safe
    end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/hashtags.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= render_with_hashtags(tweet.content) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <p flas="notice"><%= notice %></p>
  </div>
<!--Kaminari-->
  <!--<div class="container">-->
    <%= paginate @tweets %> <!-- preguntar por qué no funciona! --> 
    <%#<%= link_to_next_page @users, 'Next Page' %>
  <!--</div>-->
<!--Buscador-->
      <form class="d-flex">
        <%= search_form_for @q do |f| %> 
          <%= f.search_field :content_cont %> 
          <%= f.submit %> 
        <% end %> 
        <!--<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" >-->  
      </form>
<!--Historia nueva-->      
  <div class="container">
    <% if user_signed_in? %> 
      <div class="col-sm">
        <p>Nuevo Tweet</p>
        <%= render 'form', tweet: @tweet %>
      </div>
    <% end %>
  </div>
<!--Contenido-->  
  <div class="container">
    <div class="col-m">
      <table>
        <thead>
          <tr>
            <th>Content</th>
            <th>User</th>
            <th>Like</th>
            <th>Retweet</th>
            <!--<th>Seguidores</th>-->
            <th colspan="8"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td><%= render_with_hashtags(tweet.content) %></td>
              <td><img src="<%= tweet.user.avatar %>" class="img-thumbnail" alt="user avatar"></td> 
              <td><%= tweet.likes.size %></td>  
              <td><%= tweet.retweets.size %></td>
               
              <% if user_signed_in? %>
                <!--Boton Like-->
                <% if tweet.liked?(current_user)%> 
                  <td><%= button_to 'unlike', tweet_likes_path(tweet), method: :post %></td>
                <% else %>
                  <td><%= button_to 'like', tweet_likes_path(tweet), method: :post %></td>
                <% end %>
                <!--Retweet-->
                  <td><%= button_to 'RT', tweet_retweet_path(tweet), method: :post %></td> 
                 <!--Friend-->
                <%#<% if tweets_for_me.friend?(current_user) %>
                    <!--<td><%= button_to 'Follow', tweet_friend_path(tweet), method: :post %></td>
                <%#<% else %> 
                    <td> <%= button_to 'Unfollow', tweet_unfriend_path(tweet), method: :delete %></td>-->
                <%#<% end %>
                <!--Enlaces vistas-->
                <td><%= link_to "#{time_ago_in_words(tweet.created_at)} ago", tweet_path(tweet) %></td>  <!--ok-->
              <% end %> 
              
               <% if user_signed_in? && @tweet.user_id == current_user.id %> <!--pendiente--> 
                  <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
                  <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
               <% end %> 
            </tr>  
          <% end %> 
        </tbody>
      </table>    
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="container">
  
  <div class="container">
    <h1> Tweet </h1>
    <p><%= @tweet.user.name%></p>
    <p><img src="<%= @tweet.user.avatar %>" class="img-thumbnail" alt="user avatar"></p>
    
    <p>
      <strong>Content:</strong>
      <%= @tweet.content %>
    </p> 
    <small><%= time_ago_in_words(@tweet.created_at) %> ago</small>  
  </div>

  <div class="container">
    <strong>Like to:</strong>
    <% @tweet.likes.each do |like| %>
      <% if like.user.avatar? %>
        <p><img src="<%= like.user.avatar %>" class="img-thumbnail" alt="user avatar"></p>
      <% end %>
    <% end %>
  </div> 

  <div class="container">
    <%= link_to "Back", tweets_path %> 
  </div>
</div>
  
  